### ISSUE TITLE
sample image with instructions in docs

### ISSUE THREAD

**Issue by tacman** [genkgo/favicon#5]
I'm not able to get this to work, can you provide a sample images (png and svg) and command line in the docs please?  

```bash
curl "https://upload.wikimedia.org/wikipedia/commons/4/4b/Covetrus_Logo.png" -o logo.png
mkdir output
 ./vendor/bin/favicon-generator 'Title of the website' file:logo.png output --theme-color=#00AAAD --icon-background=#00AAAD --root=/
```

```
./vendor/bin/favicon-generator 'Title of the website' file:assets/images/books.svg output --theme-color=#00AAAD --icon-background=#00AAAD --root=/
PHP Warning:  file_put_contents(output/apple-touch-icon.png): Failed to open stream: No such file or directory in /home/tac/g/sites/hello/vendor/genkgo/favicon/bin/favicon-generator on line 170
[ERROR] Failed to save output/apple-touch-icon.png
PHP Warning:  proc_open(): posix_spawn() failed: No such file or directory in /home/tac/g/sites/hello/vendor/genkgo/favicon/src/AppleSafariPinGenerator.php on line 33
PHP Warning:  Trying to access array offset on null in /home/tac/g/sites/hello/vendor/genkgo/favicon/src/AppleSafariPinGenerator.php on line 35
PHP Fatal error:  Uncaught TypeError: stream_get_contents(): Argument #1 ($stream) must be of type resource, null given in /home/tac/g/sites/hello/vendor/genkgo/favicon/src/AppleSafariPinGenerator.php:35
Stack trace:
#0 /home/tac/g/sites/hello/vendor/genkgo/favicon/src/AppleSafariPinGenerator.php(35): stream_get_contents()
#1 /home/tac/g/sites/hello/vendor/genkgo/favicon/src/AppleSafariPinGenerator.php(68): Genkgo\Favicon\AppleSafariPinGenerator->Genkgo\Favicon\{closure}()
#2 /home/tac/g/sites/hello/vendor/genkgo/favicon/src/AppleSafariPinGenerator.php(21): Genkgo\Favicon\AppleSafariPinGenerator->tempFile()
#3 /home/tac/g/sites/hello/vendor/genkgo/favicon/src/ApplePackage.php(20): Genkgo\Favicon\AppleSafariPinGenerator->generate()
#4 /home/tac/g/sites/hello/vendor/genkgo/favicon/src/AggregatePackage.php(22): Genkgo\Favicon\ApplePackage->package()
#5 /home/tac/g/sites/hello/vendor/genkgo/favicon/src/FullPackageGenerator.php(16): Genkgo\Favicon\AggregatePackage->package()
#6 /home/tac/g/sites/hello/vendor/genkgo/favicon/bin/favicon-generator(168): Genkgo\Favicon\FullPackageGenerator->package()
#7 /home/tac/g/sites/hello/vendor/genkgo/favicon/bin/favicon-generator(177): {closure}()
#8 /home/tac/g/sites/hello/vendor/bin/favicon-generator(124): include('...')
#9 {main}
```

**Comment by skeemer** [comment]
I think this might be because you don't have  the command "potrace" installed.

**Comment by tacman** [comment]
nope, it's not that, I think it's the magick command:

      public function __construct(private readonly Input $input, private readonly string $executable = 'magick')

How do I install that on linux?  I have imagick installed, but not the standalone.

magick
Command 'magick' not found, did you mean:
  command 'magic' from deb magic (8.3.105+ds.1-1.1)
  command 'magics' from deb magics++ (4.14.2-2)
Try: sudo apt install <deb name>

**Comment by skeemer** [comment]
Oh, since you're on deb, here's the packages to support that I found.

```
sudo apt install gsfonts imagemagick potrace
```

**Comment by tacman** [comment]
sudo apt install imagemagick

no change -- magick is still not running from the CLI.

**Comment by tacman** [comment]
yep, that works, thanks!
